### ISSUE TITLE
twitter

### ISSUE THREAD

**Issue by nathanaelmartel** [chok/sfMelodyPlugin#4]
I have got a strange result while configuring the plugin with twitter : The interface is looping on the page of https://api.twitter.com/oauth/authorize and in my app, the token table is incrementing. 

I am not sure if it's an issue or a misconfiguration. My app.yml look like this : 
  melody:
    create_user: true
    twitter:
      key: xxxx
      secret: xxxx
      callback: @default_twitter
      user:
        username:  
          call: me  
          path: id  
          prefix: twitter_
        first_name:
          call: me
          path: first_name
        last_name: 
          call: me
          path: last_name
        email_address:  
          call: me  
          path: email  
          key: true  
      provider: twitter
      create_user: true  
      redirect_register: true

**Comment by chok** [comment]
with redirect_register: true it's normal :p

redirecte_register has to be a route. (need some validation :s)

create_user is not needed at the level of twitter if specfied at the parent level the provider neither because the top element is also called twitter.

And to finish, for Twitter "me" is an alias to users/show.json with the user id specified. Take a look at this page : http://dev.twitter.com/doc/get/users/show

you can for example do this:

user: 
  username: 
    call: me
    path: screen_name
    prefix: "Twitter "

Edit: I have edited your post to hide key and secret ;-)

If theses informations help you to resolve your problem. please to say it to close this issue :-)

**Comment by chok** [comment]
Closed
